# Generated by Django 4.0.4 on 2022-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='n',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
