# Generated by Django 2.1.3 on 2022-07-11 16:20

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220711_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='levels',
            field=models.PositiveIntegerField(verbose_name=myapp.models.Course),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Order Confirmed')], default=0)),
        ),
    ]
