# Generated by Django 2.1.3 on 2022-07-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220711_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='levels',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
