# Generated by Django 2.1.3 on 2022-07-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220711_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='levels',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
